
name: Test

on:
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/test.yml'
      - 'index.js'
      - 'conf/*'

jobs:
  testfreebsd:
    strategy:
      matrix:
        release: [ "", "6.9", "7.1"]
    runs-on: macos-12
    name: A job to run test OpenBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
      MYTOKEN2: "value2"
    steps:
    - uses: actions/checkout@v2
    - name: Test in OpenBSD
      id: test
      uses: vmactions/openbsd-vm@main
      with:
        envs: 'MYTOKEN MYTOKEN2'
        prepare: pkg_add curl
        mem: 2048
        release: ${{ matrix.release }}
        nat: |
          "8080": "80"
          "8443": "443"
          udp:"8081": "80"
        usesh: true
        run: |
          if [ -n "test" ]; then
            echo "false"
          fi
          if [ "test" ]; then
            echo "test"
          fi
          dmesg
          pwd
          ls -lah
          whoami
          env
          uname -a
          grep -i mem /var/run/dmesg.boot
          sysctl -a | egrep -i 'hw.machine|hw.model|hw.ncpu'
          rsync
          curl
          echo "OK"
